---
---

<link rel="stylesheet" href="styles.css" type="text/css">

<br>

I am fortunate to supervise a brilliant group of researchers.

### Postdocs

* [Andrew Cullen](https://www.linkedin.com/in/andrew-cullen-67b04746/?originalSubdomain=au) (2019-- ). Certified robustness of machine learning.
* [Neil Marchant](https://www.ngmarchant.net/) (2021-- ). Robustness, privacy, and generalisation in machine learning.
* [Ying Zhao](https://scholar.google.com/citations?user=6e-e6Q4AAAAJ) (2024-- ). Differential privacy.

### PhD students

* [Jiacheng Zhang](https://cis.unimelb.edu.au/people/students/jiacheng-zhang). (w Feng Liu 2023-- ). Trustworthy AI.
* [Maria Bulychev](https://cis.unimelb.edu.au/people/graduate-researchers/artificial-intelligence/maria-bulychev). (w Neil Marchant 2024-- ). Watermarking GenAI and trustworthy AI.
* [Wenqi Yan](https://www.linkedin.com/in/wenqi-yan-082a18223/?trk=people-guest_people_search-card&originalSubdomain=au). (w Thuan Pham, Toby Murray 2024-- ). Software fuzzing with LLMs.
* [Jiani Xie](https://www.linkedin.com/in/jiani-xie-a79a67152/?originalSubdomain=au). (w Andrew Cullen 2025-- ). Security of automatic speech recognition.

### PhD students---Completed

* [Zhuoqun (Calvin) Huang](https://github.com/Dovermore). (w Olya Ohrimenko, Neil Marchant 2021--25). Certified robustness for discrete data → Quant at Jane Street
* [Shijie Liu](https://www.linkedin.com/in/shijie-liu-9162b8151/). (w Sarah Erfani, Paul Montague, Andrew Cullen 2021-25). Certified robustness at training time → Postdoc at Univ Melbourne
* [Jiankai Jin](https://www.linkedin.com/in/jin-jiankai-3a5750119/). (w Olya Ohrimenko 2021--25). Systems security of differential privacy → Senior AI Security Research Engineer at 360 Security
* [Jun Wang](https://www.linkedin.com/in/jun-wang-15065b170/). (w Trevor Cohn 2020-25). Adversarial learning for NLP → Postdoc (Applied Scientist) at Amazon
* [Guoxin Sun](https://www.linkedin.com/in/guoxin-sun-338888162/). (w Tansu Alpcan, Seyit Camtepe 2020--24). Adversarial learning/game theory for autonomous systems → Data scientist at Proa
* [Ruihan Zhang](https://scholar.google.com/citations?user=gjSlsnQAAAAJ&hl=en) (w Tim Miller, Kris Ehinger 2019--24). Explainable AI →  Postdoc at the State Grid Corporation of China
* [Malinga Perera](http://www.malinga.me/) (w Renata Borovica-Gajic 2018--23). Self-driving databases → Software engineer at Amazon Web Services
* [Bastian Oetomo](https://www.linkedin.com/in/bastian-oetomo-34300856/) (w Renata Borovica-Gajic 2018--23). Multi-armed bandits for database index selection → Postdoc at Univ Melbourne
* [Dongge Liu](https://www.linkedin.com/in/dongge-liu-9a957913a) (w Toby Murray, Thuan Pham, Gidon Ernst at LMU Munich 2018--22). Software fuzzing with machine learning → Open-Source Security at Google
* [Neil Marchant](https://www.ngmarchant.net/) (w Beka Steorts at Duke, Aurore Delaigle 2016--20). Bayesian record linkage, adaptive importance sampling for efficient evaluation → Postdoc at Univ Melbourne
* [Leyla Roohi](https://au.linkedin.com/in/leyla-roohi-b4544a67) (w Vanessa Teague 2017--19). Secure storage and private querying for telecommunications metadata → Postdoc at Univ Melbourne → Analytics at National Australia Bank
* [Yuan Li](https://scholar.google.com/citations?user=qDDC09EAAAAJ&hl=en) (w Trevor Cohn 2015--19). Crowd sourcing, Bayesian optimisation, NLP → Postdoc at Univ Melbourne
* [Lingjuan Lyu](https://www.researchgate.net/profile/Lingjuan_Lyu) (w Marimuthu Palaniswami 2016--18). Privacy in distributed sensing → Postdoc at the ANU → Head of Privacy and Security, Sony AI
* [Safiollah Heidari](https://sites.google.com/site/safiheidari/) (w Raj Buyya 2015--18). Distributed graph processing → Founder of NeuroPhyte
* [Xunyun Liu](https://xunyunliu.github.io/) (w Raj Buyya, Rodrigo Calheiros 2015--18). Stream computing → Assistant Prof at NUDT, China
* [Zay Aye](https://www.researchgate.net/profile/Zay_Aye) - CompSci (w Rao Kotagiri 2014--18). Learning distance metrics → Postdoc at Univ Melbourne (Infrastructure Engineering)
* [Yamuna Kankanige](https://www.linkedin.com/in/yamuna-kankanige-8b258a26/) (w James Bailey 2015--18). Predicting liver transplant outcomes with Austin Health → Senior Data Scientist, Peter MacCallum Cancer Centre
* [Maryam Fanaeepour](https://scholar.google.com.au/citations?user=1EPDwbAAAAAJ&hl=en) - CompSci (w Lars Kulik, Egemen Tanin 2014--17). Location data privacy → Postdoc at Duke University → Specialist Manager, Data Science, Privacy, Trust at Deloitte
* [Jiazhen He](https://scholar.google.com.au/citations?user=GtpWKiwAAAAJ&hl=en) - CompSci (w James Bailey, Rui Zhang 2014--17). Education analytics and MOOCs → Postdoc at Univ Melbourne → Associate Principal AI Scientist, AstraZeneca
* [Zuhe Zhang](https://www.researchgate.net/profile/Zuhe_Zhang) - Maths & Stats (w Sanming Zhou 2014--17). Differential privacy in Bayesian statistics → Data Scientist at ANZ Bank → Data Scientist at Officeworks

### Other Alumni

* [Aref Miri Rekavandi](https://arekavandi.github.io/) (psotdoc 2023--24). Certified robustness  →  Postdoc, University of Oxford
* [Amila Silva](https://www.amilasilva.com/) (postdoc 2023--23). Multi-modal learning for human-AI teaming →  Machine Learning Engineer, Canva
* [Ni Ding](https://profiles.auckland.ac.nz/ni-ding) (postdoc 2020-23). Information theory for privacy → Lecturer, Univ Auckland, New Zealand 
* [Sandamal Weerasinghe](https://cis.unimelb.edu.au/people/prameesha-weerasinghe) (postdoc 2019--21). Adversarial machine learning → Energy and Forecasting Analyst, ZEN Energy (startup)
* [Roei Gelbhart](https://scholar.google.co.il/citations?user=en8SzLcAAAAJ&hl=en) (student 2019--21). Robustness in machine learning → Applied Scientist, Amazon, Haifa.
* [Chang Xu](https://changxu.io/) (postdoc 2020--21). Adversarial learning for NLP → Data Scientist, News Corp, Sydney.
* [Shuo Zhou](https://shuozhou.github.io/) (postdoc w Tordesillas, Bailey, Bondell 2019--20). Complex networks in materials science, cybersecurity.
* [Thibaut Lienart](https://tlienart.github.io/) (postdoc 2018--19). Adversarial machine learning → Associate, Alan Turing Institute
* [Yi Han](https://scholar.google.com/citations?user=e_mtK4kAAAAJ&hl=en) (postdoc 2016--19). Adversarial reinforcement learning → Postdoc at Melbourne
* [Shen Wang](https://scholar.google.com/citations?user=TpErHPkAAAAJ&hl=en) (postdoc 2016--18). Probabilistic programming, databases, record linkage.
* [Ben Fish](http://ben.fish/) (medium-term PhD visitor 2016) → Postdoc at MSR Montréal
* [Francesco Aldà](http://www.ruhr-uni-bochum.de/lmi/alda/) (medium-term PhD visitor 2016) → Data Scientist at SAP, Germany
<!-- ### PhD interns---former Microsoft Research -->
* [Akshay Balsubramani](http://www.linkedin.com/pub/akshay-balsubramani/12/3aa/2) (MSR PhD intern 2012) → Postdoc at Stanford
* [Emanuele Coviello](http://acsweb.ucsd.edu/~ecoviell/) (MSR PhD intern 2012) → Founder/CEO at Keevio
* [Sahand Negahban](http://www.eecs.berkeley.edu/~sahand_n/) (MSR PhD intern 2011) → Assistant Prof at Yale Statistics
* [Duo Zhang](http://sifaka.cs.uiuc.edu/~dzhang22/) (MSR PhD intern 2011) → Software Engineer at Twitter
* [Bo Zhao](http://dm1.cs.uiuc.edu/) (MSR PhD intern 2011) → Researcher at Microsoft Research
